[package]
name = "cargo-hack"
version = "0.5.23"
edition = "2021"
rust-version = "1.60"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/cargo-hack"
keywords = ["cargo", "subcommand", "testing"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::testing"]
exclude = ["/.*", "/tools"]
description = """
Cargo subcommand to provide various options useful for testing and continuous integration.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[workspace]
resolver = "2"
members = ["tests/auxiliary/build-info"]

[dependencies]
anyhow = "1.0.47"
ctrlc = { version = "3.1.4", features = ["termination"] }
indexmap = { version = "1.5.2", features = ["std"] }
is-terminal = "0.4"
lexopt = "0.2"
serde_json = "1"
termcolor = "1.1"
toml_edit = "0.15"

[dev-dependencies]
build-info = { path = "tests/auxiliary/build-info" }
easy-ext = "1"
fs-err = "2"
once_cell = "1"
tempfile = "3"
walkdir = "2"

[profile.release]
strip = "symbols"
