name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - staging
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: nightly
            os: macos-latest
          - rust: nightly
            os: windows-latest
    runs-on: ${{ matrix.os || 'ubuntu-18.04' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: ${{ matrix.rust }}
      - uses: taiki-e/install-action@cargo-hack
        if: startsWith(matrix.rust, 'nightly')
      - uses: taiki-e/install-action@cargo-minimal-versions
        if: startsWith(matrix.rust, 'nightly')
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: startsWith(matrix.os, 'windows')
      - run: cargo test --workspace
      - run: cargo minimal-versions build --workspace --all-features --ignore-private
        if: startsWith(matrix.rust, 'nightly')

  cross:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.os || 'ubuntu-18.04' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
      - uses: taiki-e/install-action@cross
      - run: cross test --target ${{ matrix.target }}

  test-compat:
    name: test (1.${{ matrix.rust }})
    strategy:
      fail-fast: false
      matrix:
        rust:
          # cargo-hack is usually runnable with Cargo versions older than the Rust version required for installation.
          # When updating this, the reminder to update the minimum supported Rust version in README.md.
          - 26
          - 30
          - 31
          - 36
          - 39
          - 41
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
      - run: CARGO_HACK_TEST_TOOLCHAIN=${{ matrix.rust }} cargo test --workspace
      # Remove stable toolchain to disable https://github.com/taiki-e/cargo-hack/pull/138's behavior.
      - run: rustup toolchain remove stable
      - run: CARGO_HACK_TEST_TOOLCHAIN=${{ matrix.rust }} cargo test --workspace

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack build --workspace --ignore-private --no-dev-deps --version-range .. --version-step 2

  fuzz:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
      - uses: dtolnay/install@cargo-fuzz
      - run: cargo install afl --debug
      - run: cargo fuzz build
      - run: cargo afl build
        working-directory: fuzz/afl

  tidy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          component: clippy,rustfmt
      - uses: taiki-e/install-action@shellcheck
      - run: cargo fmt --all -- --check
        if: always()
      - run: cargo clippy --workspace --all-features --all-targets
        if: always()
      - run: shellcheck $(git ls-files '*.sh')
        if: always()

  # This job doesn't actually test anything, but they're used to tell bors the
  # build completed, as there is no practical way to detect when a workflow is
  # successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEEDS TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  ci-success:
    name: ci
    if: github.event_name == 'push' && success()
    needs:
      - test
      - test-compat
      - build
      - fuzz
      - tidy
    runs-on: ubuntu-18.04
    steps:
      - name: Mark the job as a success
        run: exit 0
